/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Nicolas
 */
public class Datos extends javax.swing.JFrame {

    private Principal principal;
    private final ProductosPedir productosPedir;
    
    fondoPanel fondo = new fondoPanel();

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }

    public Datos() {
        this.setContentPane(fondo);
        initComponents();
        productosPedir = new ProductosPedir();
        
        String root = "src\\imagenes\\Imagen.jpg";
        setImagenLabel(imagenLabel, root);

    }

    private void setImagenLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(
                        labelName.getWidth(),
                        labelName.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        labelName.setIcon(icon);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGen = new javax.swing.ButtonGroup();
        jLabelDatos = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelApe = new javax.swing.JLabel();
        jLabelCo = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelGen = new javax.swing.JLabel();
        rbtnMujer = new javax.swing.JRadioButton();
        rbtnHombre = new javax.swing.JRadioButton();
        txtNom = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        spEdad = new javax.swing.JSpinner();
        btnSiguiente = new javax.swing.JButton();
        jLabelDir = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDatos.setBackground(new java.awt.Color(153, 0, 0));
        jLabelDatos.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelDatos.setForeground(new java.awt.Color(153, 0, 0));
        jLabelDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatos.setText("Datos Personales");

        jLabelNom.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelNom.setText("Nombre:");

        jLabelApe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelApe.setText("Apellidos:");

        jLabelCo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelCo.setText("Correo:");

        jLabelEdad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelEdad.setText("Edad:");

        jLabelGen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelGen.setText("Genero:");

        btgGen.add(rbtnMujer);
        rbtnMujer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbtnMujer.setText("Mujer");
        rbtnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMujerActionPerformed(evt);
            }
        });

        btgGen.add(rbtnHombre);
        rbtnHombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbtnHombre.setText("Hombre");

        txtNom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtApe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        spEdad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnSiguiente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabelDir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelDir.setText("Dirección:");

        txtDirec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAtras.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabelDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelApe, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                            .addComponent(txtApe))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelGen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(rbtnMujer)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnHombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNom)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApe)
                            .addComponent(jLabelApe, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo)
                            .addComponent(jLabelCo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(txtDirec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnMujer)
                            .addComponent(rbtnHombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMujerActionPerformed


    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        String genero = "";
        if (Datos.rbtnMujer.isSelected()) {
            genero = "Mujer";
        } else {
            genero = "Hombre";
        }

        String nom = txtNom.getText();
        String apellido = txtApe.getText();
        int edad = Integer.parseInt(spEdad.getValue().toString());
        String correo = txtCorreo.getText();
        String direccion = txtDirec.getText();

        productosPedir.setDatos(this);
        productosPedir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnSiguienteActionPerformed


    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        principal.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGen;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel imagenLabel;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelCo;
    private javax.swing.JLabel jLabelDatos;
    private javax.swing.JLabel jLabelDir;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelGen;
    private javax.swing.JLabel jLabelNom;
    protected static javax.swing.JRadioButton rbtnHombre;
    protected static javax.swing.JRadioButton rbtnMujer;
    protected static javax.swing.JSpinner spEdad;
    protected static javax.swing.JTextField txtApe;
    protected static javax.swing.JTextField txtCorreo;
    protected static javax.swing.JTextField txtDirec;
    protected static javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
class fondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/Fondo.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }

}
